#/******************************************************************
# * muensterTPCsim
# * 
# * Simulations of the Muenster TPC
# * 
# * @author Lutz Althüser
# * @date   2015-04-14
# *
# * @comment beam test
# ******************************************************************/
/tracking/verbose 2
/Xe/gun/particle opticalphoton
/Xe/gun/position  13 0 8 mm
/Xe/gun/direction 0 0 1
/Xe/gun/energy 7 eV

/run/beamOn 1
