# Change the default number of threads (in multi-threaded mode)
# /run/numberOfThreads 4
#
# Initialize kernel
/run/verbose 0
/control/verbose 0

/run/physics/setEMlowEnergyModel emlivermore
/run/physics/setHadronicModel QGSP_BERT_HP
/run/physics/setCerenkov false

/run/initialize
#
# Set some default verbose
/control/verbose 2
/control/saveHistory
/run/verbose 2
#
# Visualization setting
# /control/execute vis.mac <- is done by the simulation.
